### ISSUE TITLE
tensorflow example: don't load saved model

### ISSUE THREAD

**Issue by IvanKush** [mwydmuch/ViZDoom#207]
after training trying to load a model, set `load_model = True`:

```
unfile('/home/df/projects/python/vizdoom/ViZDoom-master/examples/python/df_vzd.py', wdir='/home/df/projects/python/vizdoom/ViZDoom-master/examples/python')
Initializing doom...
Doom initialized.
Loading model from:  ./ckpt/model.ckpt
INFO:tensorflow:Restoring parameters from ./ckpt/model.ckpt
Restoring parameters from ./ckpt/model.ckpt
Traceback (most recent call last):

  File "<ipython-input-79-8e14ee900dde>", line 1, in <module>
    runfile('/home/df/projects/python/vizdoom/ViZDoom-master/examples/python/df_vzd.py', wdir='/home/df/projects/python/vizdoom/ViZDoom-master/examples/python')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/df/projects/python/vizdoom/ViZDoom-master/examples/python/df_vzd.py", line 228, in <module>
    saver.restore(session, model_savefile)

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1555, in restore
    {self.saver_def.filename_tensor_name: save_path})

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 896, in run
    run_metadata_ptr)

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1108, in _run
    feed_dict_tensor, options, run_metadata)

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1261, in _do_run
    options, run_metadata)

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1280, in _do_call
    raise type(e)(node_def, op, message)

NotFoundError: Key Conv_21/biases not found in checkpoint
	 [[Node: save_13/RestoreV2_84 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_13/Const_0_0, save_13/RestoreV2_84/tensor_names, save_13/RestoreV2_84/shape_and_slices)]]

Caused by op 'save_13/RestoreV2_84', defined at:
  File "/usr/lib/python3/dist-packages/spyder/utils/ipython/start_kernel.py", line 227, in <module>
    main()
  File "/usr/lib/python3/dist-packages/spyder/utils/ipython/start_kernel.py", line 223, in main
    kernel.start()
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/lib/python3/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python3/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python3/dist-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-79-8e14ee900dde>", line 1, in <module>
    runfile('/home/df/projects/python/vizdoom/ViZDoom-master/examples/python/df_vzd.py', wdir='/home/df/projects/python/vizdoom/ViZDoom-master/examples/python')
  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/home/df/projects/python/vizdoom/ViZDoom-master/examples/python/df_vzd.py", line 225, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 661, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2528, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1203, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key Conv_21/biases not found in checkpoint
	 [[Node: save_13/RestoreV2_84 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_13/Const_0_0, save_13/RestoreV2_84/tensor_names, save_13/RestoreV2_84/shape_and_slices)]]

```

**Comment by ebonyclock** [comment]
Quite peculiar. It works on my machine for python2, 3, gpu, cpu .... What is this unfile command?

**Comment by GoingMyWay** [comment]
Have you ever changed the code? It seems that in your code there is no value named `Conv_21/biases`. Please check names when you defined the weights and biases with TensorFlow.
