### ISSUE TITLE
ImportError: dlopen(.../vizdoom.so) on mac

### ISSUE THREAD

**Issue by njustesen** [mwydmuch/ViZDoom#246]
Hi,

I managed to build VizDoom on mac following the instuctions, but I get an import error when I try to use it:

$ python basic.py 
Traceback (most recent call last):
  File "basic.py", line 15, in <module>
    from vizdoom import *
  File "/usr/local/lib/python2.7/site-packages/vizdoom/__init__.py", line 1, in <module>
    from .vizdoom import __version__ as __version__
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/vizdoom/vizdoom.so, 2): Symbol not found: __ZN5boost6python7numeric5array19set_module_and_typeEPKcS4_
  Referenced from: /usr/local/lib/python2.7/site-packages/vizdoom/vizdoom.so
  Expected in: /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
 in /usr/local/lib/python2.7/site-packages/vizdoom/vizdoom.so

Any ideas?

**Comment by mwydmuch** [comment]
Hi @njustesen, good to see you here :)
It looks like a some kind of problem with numpy that was used to build vizdoom.so. I will try to reproduce it. Could you post more details about how you build vizdoom? CMake output would be really helpful.

**Comment by njustesen** [comment]
Hi Marek :)
I think you are right
```
Nielss-MacBook-Pro:VizDoom` noju$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON
CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:88 (find_package)


-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   date_time
--   chrono
--   regex
--   iostreams
CMake Deprecation Warning at cmake_modules/CreateLaunchers.cmake:48 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  src/vizdoom/CMakeLists.txt:13 (include)


-- Could NOT find GME (missing: GME_LIBRARIES GME_INCLUDE_DIR) 
-- Using system zlib
-- Using system jpeg library
-- Using system bzip2 library
-- Using internal gme library
-- /usr/include
-- /usr/include
-- /Users/noju/Documents/VizDoom/src/vizdoom/lzma/C
-- Could not find FMOD include files
-- Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR) 
-- Could NOT find MPG123 (missing: MPG123_LIBRARIES MPG123_INCLUDE_DIR) 
-- Could NOT find FluidSynth (missing: FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR) 
-- Could not find clock_gettime. Timing statistics will not be available.
CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  src/vizdoom/src/CMakeLists.txt:559 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  src/vizdoom/src/CMakeLists.txt:559 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  src/vizdoom/src/CMakeLists.txt:559 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  src/vizdoom/src/CMakeLists.txt:559 (find_package)


-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
-- Fluid synth libs: FLUIDSYNTH_LIBRARIES-NOTFOUND
-- Found components for NumPy
-- NUMPY_ROOT_DIR    = /usr/local
-- NUMPY_INCLUDES    = /usr/local/lib/python2.7/site-packages/numpy/core/include
-- NUMPY_LIBRARIES   = 
-- NUMPY_API_VERSION = 1.13.1
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/noju/Documents/VizDoom
```

Also when I run `make`:
```
...
1 warning generated.
darwin.compile.c++ bin.v2/libs/python/build/darwin-4.2.1/release/link-static/threading-multi/numpy/ufunc.o
In file included from libs/python/src/numpy/ufunc.cpp:8:
In file included from ./boost/python/numpy/internal.hpp:28:
In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:
/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
1 warning generated.
darwin.archive bin.v2/libs/python/build/darwin-4.2.1/release/link-static/threading-multi/libboost_numpy.a
common.copy stage/lib/libboost_numpy.a
...updated 17 targets...


The Boost C++ Libraries were successfully built!
...
```

**Comment by njustesen** [comment]
I reinstalled everything and now I have issue #243 as well.
