### ISSUE TITLE
Vizdoom crashes after installation  

### ISSUE THREAD

**Issue by rasoolfa** [mwydmuch/ViZDoom#287]
Hi,

I have "successfully" installed ViZDoom on my Linux machine using pip. However, whenever I try to run the basic.py example, it fails and prints the followings in the output and crash_log file:

```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: alsa_open_playback: Could not open playback device 'default': No such file or directory
```

and vizdoom-crash.log:

```
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

System: Linux thebe 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

ViZDoom version 1.1.4 (ZDOOM 2.8.1) ()
Compiler version: 4.8.4

Command line: /usr/local/lib/python2.7/dist-packages/vizdoom/vizdoom -iwad /usr/local/lib/python2.7/dist-packages/vizdoom/freedoom2.wad -config _vizdoom.ini -skill 3 -width 640 -height 480 +vid_aspect 3 +fullscreen 0 +viz_controlled 1 +viz_instance_id uGri0c5LXs +use_mouse 0 -rngseed 1735077088 +viz_depth 1 +viz_labels 1 +viz_automap 1 +viz_automap_mode 0 +viz_render_mode 2564 +viz_noconsole 1 +viz_screen_format 1 -noidle -nojoy -file ../../scenarios/basic.wad

Wad 0: vizdoom.pk3
Wad 1: freedoom2.wad
Wad 2: basic.wad

Not in a level.

Executing: gdb --quiet --batch --command=gdb-respfile-yebzxy
[New LWP 22171]
[New LWP 22170]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f1e71b79ee9 in __libc_waitpid (pid=22195, stat_loc=0xbb9e20, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40

* Loaded Libraries
From                To                  Syms Read   Shared Object Library
0x00007f1e7264fe40  0x00007f1e72899aae  Yes (*)     /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
0x00007f1e723a02a0  0x00007f1e723ce0c6  Yes (*)     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
0x00007f1e720a78c0  0x00007f1e7211ab2a  Yes (*)     /lib/x86_64-linux-gnu/libglib-2.0.so.0
0x00007f1e71da0280  0x00007f1e71e4e83a  Yes (*)     /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
0x00007f1e71b6f9f0  0x00007f1e71b7c4a1  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x00007f1e71964350  0x00007f1e7196733c  Yes         /lib/x86_64-linux-gnu/librt.so.1
0x00007f1e7174ae00  0x00007f1e7175abf8  Yes (*)     /lib/x86_64-linux-gnu/libz.so.1
0x00007f1e714f7d90  0x00007f1e7152e520  Yes (*)     /usr/lib/x86_64-linux-gnu/libjpeg.so.8
0x00007f1e712e53c0  0x00007f1e712f108f  Yes (*)     /lib/x86_64-linux-gnu/libbz2.so.1.0
0x00007f1e710d8f40  0x00007f1e710de883  Yes (*)     /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
0x00007f1e70ecb250  0x00007f1e70ecbdc3  Yes (*)     /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0
0x00007f1e70c68130  0x00007f1e70ca8ffc  Yes (*)     /usr/lib/x86_64-linux-gnu/libsndfile.so.1
0x00007f1e70a5eed0  0x00007f1e70a5f9ce  Yes         /lib/x86_64-linux-gnu/libdl.so.2
0x00007f1e707b5620  0x00007f1e70818803  Yes (*)     /usr/lib/x86_64-linux-gnu/libstdc++.so.6
0x00007f1e70459610  0x00007f1e704c81b6  Yes         /lib/x86_64-linux-gnu/libm.so.6
0x00007f1e70240ab0  0x00007f1e70250985  Yes (*)     /lib/x86_64-linux-gnu/libgcc_s.so.1
0x00007f1e6fe984a0  0x00007f1e6ffdd583  Yes         /lib/x86_64-linux-gnu/libc.so.6
0x00007f1e6fbe3910  0x00007f1e6fc380eb  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
0x00007f1e6f9c3150  0x00007f1e6f9c4015  Yes (*)     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
0x00007f1e6f7b98d0  0x00007f1e6f7be216  Yes (*)     /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
0x00007f1e6f4987f0  0x00007f1e6f51bbfb  Yes (*)     /usr/lib/x86_64-linux-gnu/libX11.so.6
0x00007f1e6f27b530  0x00007f1e6f27d766  Yes (*)     /usr/lib/x86_64-linux-gnu/libXfixes.so.3
0x00007f1e6f061990  0x00007f1e6f06d183  Yes (*)     /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
0x00007f1e6ed5e940  0x00007f1e6ee1a016  Yes (*)     /usr/lib/x86_64-linux-gnu/libcairo.so.2
0x00007f1e6eb31e30  0x00007f1e6eb43bb0  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
0x00007f1e6e7ec790  0x00007f1e6e8b2a2b  Yes (*)     /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
0x00007f1e6e5ab360  0x00007f1e6e5b354b  Yes (*)     /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
0x00007f1e6e364e50  0x00007f1e6e383f26  Yes (*)     /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
0x00007f1e6e121c80  0x00007f1e6e13e589  Yes (*)     /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
0x00007f1e6df14650  0x00007f1e6df18d38  Yes (*)     /usr/lib/x86_64-linux-gnu/libffi.so.6
0x00007f1e6dcd67b0  0x00007f1e6dcfcadf  Yes (*)     /lib/x86_64-linux-gnu/libpcre.so.3
0x00007f1e6da0ef80  0x00007f1e6da939a2  Yes (*)     /usr/lib/x86_64-linux-gnu/libasound.so.2
0x00007f1e6d7e2550  0x00007f1e6d7e3733  Yes (*)     /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
0x00007f1e6d5a3170  0x00007f1e6d5cdcd8  Yes (*)     /usr/lib/x86_64-linux-gnu/libpulse.so.0
0x00007f1e6d389580  0x00007f1e6d392c7f  Yes (*)     /usr/lib/x86_64-linux-gnu/libXext.so.6
0x00007f1e6d17e420  0x00007f1e6d182e20  Yes (*)     /usr/lib/x86_64-linux-gnu/libXcursor.so.1
0x00007f1e6cf79af0  0x00007f1e6cf7a3ec  Yes (*)     /usr/lib/x86_64-linux-gnu/libXinerama.so.1
0x00007f1e6cd6b1e0  0x00007f1e6cd74f12  Yes (*)     /usr/lib/x86_64-linux-gnu/libXi.so.6
0x00007f1e6cb60ad0  0x00007f1e6cb65fd8  Yes (*)     /usr/lib/x86_64-linux-gnu/libXrandr.so.2
0x00007f1e6c95bcd0  0x00007f1e6c95ca8c  Yes (*)     /usr/lib/x86_64-linux-gnu/libXss.so.1
0x00007f1e6c755f40  0x00007f1e6c7586f6  Yes (*)     /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1
0x00007f1e6c5536e0  0x00007f1e6c553896  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
0x00007f1e6c34ab90  0x00007f1e6c34ebcf  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
0x00007f1e6c13f200  0x00007f1e6c140c4c  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0
0x00007f1e6bf07f10  0x00007f1e6bf1f1d5  Yes (*)     /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0
0x00007f1e72c23ae0  0x00007f1e72c3e4e0  Yes         /lib64/ld-linux-x86-64.so.2
0x00007f1e6bcdb300  0x00007f1e6bcf998d  Yes (*)     /usr/lib/x86_64-linux-gnu/libFLAC.so.8
0x00007f1e6b817a40  0x00007f1e6b819ff4  Yes (*)     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
0x00007f1e6b5d9dd0  0x00007f1e6b5f133d  Yes (*)     /usr/lib/x86_64-linux-gnu/libvorbis.so.0
0x00007f1e6b3cfa70  0x00007f1e6b3d3c25  Yes (*)     /usr/lib/x86_64-linux-gnu/libogg.so.0
0x00007f1e6b1c5a60  0x00007f1e6b1cb728  Yes (*)     /usr/lib/x86_64-linux-gnu/libXrender.so.1
0x00007f1e6afc1c40  0x00007f1e6afc2618  Yes (*)     /usr/lib/x86_64-linux-gnu/libXcomposite.so.1
0x00007f1e6adbeb90  0x00007f1e6adbf49b  Yes (*)     /usr/lib/x86_64-linux-gnu/libXdamage.so.1
0x00007f1e6ab26b90  0x00007f1e6ab9227d  Yes (*)     /usr/lib/x86_64-linux-gnu/libfreetype.so.6
0x00007f1e6a905620  0x00007f1e6a9115e5  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb.so.1
0x00007f1e6a65e4e0  0x00007f1e6a6e3c2c  Yes (*)     /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
0x00007f1e6a431ab0  0x00007f1e6a44b003  Yes (*)     /lib/x86_64-linux-gnu/libpng12.so.0
0x00007f1e6a22bd80  0x00007f1e6a22c5f3  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
0x00007f1e6a025430  0x00007f1e6a027edf  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
0x00007f1e69e04b00  0x00007f1e69e16a26  Yes (*)     /lib/x86_64-linux-gnu/libselinux.so.1
0x00007f1e69be7ad0  0x00007f1e69bf6e69  Yes         /lib/x86_64-linux-gnu/libresolv.so.2
0x00007f1e69994f20  0x00007f1e699c865a  Yes (*)     /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
0x00007f1e69787c20  0x00007f1e6978b011  Yes (*)     /usr/lib/x86_64-linux-gnu/libthai.so.0
0x00007f1e6955fb90  0x00007f1e69578769  Yes (*)     /lib/x86_64-linux-gnu/libexpat.so.1
0x00007f1e69305180  0x00007f1e6933f44a  Yes (*)     /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-4.0.so
0x00007f1e690ec800  0x00007f1e690f13cb  Yes (*)     /lib/x86_64-linux-gnu/libjson-c.so.2
0x00007f1e68eab840  0x00007f1e68ed3d74  Yes (*)     /lib/x86_64-linux-gnu/libdbus-1.so.3
0x00007f1e68ca1e50  0x00007f1e68ca2acc  Yes (*)     /usr/lib/x86_64-linux-gnu/libXau.so.6
0x00007f1e68a9c350  0x00007f1e68a9dd6c  Yes (*)     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
0x00007f1e68881410  0x00007f1e6889345c  Yes (*)     /usr/lib/x86_64-linux-gnu/libgraphite2.so.3
0x00007f1e68679170  0x00007f1e6867c274  Yes (*)     /usr/lib/x86_64-linux-gnu/libdatrie.so.1
0x00007f1e68470d70  0x00007f1e68474798  Yes (*)     /lib/x86_64-linux-gnu/libwrap.so.0
0x00007f1e68269370  0x00007f1e6826b8e8  Yes (*)     /usr/lib/x86_64-linux-gnu/libasyncns.so.0
0x00007f1e68052160  0x00007f1e6805eea3  Yes         /lib/x86_64-linux-gnu/libnsl.so.1
0x00007f1e67b59710  0x00007f1e67b7e1f4  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
0x00007f1e679500b0  0x00007f1e67952070  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
0x00007f1e6774abf0  0x00007f1e6774c00e  Yes (*)     /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0
0x00007f1e6753bbe0  0x00007f1e675447ab  Yes (*)     /usr/lib/x86_64-linux-gnu/libcanberra.so.0
0x00007f1e67332da0  0x00007f1e67336f0c  Yes (*)     /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3
0x00007f1e671212a0  0x00007f1e6712b052  Yes (*)     /usr/lib/x86_64-linux-gnu/libtdb.so.1
0x00007f1e66f174b0  0x00007f1e66f1b676  Yes (*)     /usr/lib/x86_64-linux-gnu/libltdl.so.7
0x00007f1e66d07010  0x00007f1e66d0f750  Yes (*)     /lib/x86_64-linux-gnu/libudev.so.1
0x00007f1e66aec610  0x00007f1e66afe6ec  Yes (*)     /lib/x86_64-linux-gnu/libcgmanager.so.0
0x00007f1e668d5760  0x00007f1e668e212a  Yes (*)     /lib/x86_64-linux-gnu/libnih.so.1
0x00007f1e666c9ce0  0x00007f1e666cd4c6  Yes (*)     /lib/x86_64-linux-gnu/libnih-dbus.so.1
0x00007f1e664752e0  0x00007f1e664a43a4  Yes (*)     /usr/lib/x86_64-linux-gnu/libopenal.so
0x00007f1e64043710  0x00007f1e6404793b  Yes (*)     /usr/lib/nvidia-367/libGL.so.1
0x00007f1e5f5d1770  0x00007f1e5f5dba2d  Yes (*)     /usr/lib/nvidia-367/libGLX.so.0
0x00007f1e5f310cc0  0x00007f1e5f3321b1  Yes (*)     /usr/lib/nvidia-367/libGLdispatch.so.0
0x00007f1e5ee89de0  0x00007f1e5ee8b174  Yes (*)     /usr/lib/nvidia-367/libEGL.so.1
0x00007f1e5eba29b0  0x00007f1e5ec33b38  Yes (*)     /usr/lib/nvidia-367/libEGL_nvidia.so.0
0x00007f1e5e8f94e0  0x00007f1e5e961c98  Yes (*)     /usr/lib/nvidia-367/libnvidia-glsi.so.367.57
0x00007f1e5e6f2ce0  0x00007f1e5e6f4e98  Yes (*)     /usr/lib/nvidia-367/libnvidia-egl-wayland.so.367.57
0x00007f1e5e4e5ae0  0x00007f1e5e4eaf6f  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
0x00007f1e5e2d2380  0x00007f1e5e2d9648  Yes (*)     /usr/lib/nvidia-367/libGLESv2_nvidia.so.2
0x00007f1e5ca301c0  0x00007f1e5d995a47  Yes (*)     /usr/lib/nvidia-367/libnvidia-eglcore.so.367.57
(*): Shared library is missing debugging information.

* Threads
  Id   Target Id         Frame 
  3    Thread 0x7f1e6646d700 (LWP 22170) "SDLTimer" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  2    Thread 0x7f1e72e379c0 (LWP 22171) "vizdoom" 0x00007f1e71966fe7 in timer_helper_thread (arg=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/timer_routines.c:92
* 1    Thread 0x7f1e72ded9c0 (LWP 22168) "vizdoom" 0x00007f1e71b79ee9 in __libc_waitpid (pid=22195, stat_loc=0xbb9e20, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40

* FPU Status
  R7: Empty   0x00000000000000000000
  R6: Empty   0x00000000000000000000
  R5: Empty   0x00000000000000000000
  R4: Empty   0x00000000000000000000
  R3: Empty   0x00000000000000000000
  R2: Empty   0x00000000000000000000
  R1: Empty   0x00000000000000000000
=>R0: Empty   0x00000000000000000000

Status Word:         0x0000                                            
                       TOP: 0
Control Word:        0x027f   IM DM ZM OM UM PM
                       PC: Double Precision (53-bits)
                       RC: Round to nearest
Tag Word:            0xffff
Instruction Pointer: 0x7f1e:0x7080af38
Operand Pointer:     0x7ffd:0x576c91b8
Opcode:              0x0000

* Registers
rax            0xfffffffffffffe00	-512
rbx            0x56b3	22195
rcx            0xffffffffffffffff	-1
rdx            0x0	0
rsi            0xbb9e20	12295712
rdi            0x56b3	22195
rbp            0xbb9e20	0xbb9e20
rsp            0xbb9e00	0xbb9e00
r8             0x0	0
r9             0x1	1
r10            0x0	0
r11            0x246	582
r12            0xb	11
r13            0x1090	4240
r14            0xbb7300	12284672
r15            0xd	13
rip            0x7f1e71b79ee9	0x7f1e71b79ee9 <__libc_waitpid+105>
eflags         0x246	[ PF ZF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

* Backtrace

Thread 3 (Thread 0x7f1e6646d700 (LWP 22170)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
No locals.
#1  0x00007f1e71e4958e in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#2  0x00007f1e71e496d5 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#3  0x00007f1e71dfebb1 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#4  0x00007f1e71dfe74d in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#5  0x00007f1e71e492d9 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#6  0x00007f1e71b72182 in start_thread (arg=0x7f1e6646d700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f1e6646d700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139768541665024, -842023072022440978, 0, 0, 139768541665728, 139768541665024, 751051068500825070, 751092973284971502}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f1e6ff7347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 2 (Thread 0x7f1e72e379c0 (LWP 22171)):
#0  0x00007f1e71966fe7 in timer_helper_thread (arg=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/timer_routines.c:92
        resultvar = <optimized out>
        si = {si_signo = 32, si_errno = 0, si_code = -2, _sifields = {_pad = {1, 0, 46527424, 0 <repeats 25 times>}, _kill = {si_pid = 1, si_uid = 0}, _timer = {si_tid = 1, si_overrun = 0, si_sigval = {sival_int = 46527424, sival_ptr = 0x2c5f3c0}}, _rt = {si_pid = 1, si_uid = 0, si_sigval = {sival_int = 46527424, sival_ptr = 0x2c5f3c0}}, _sigchld = {si_pid = 1, si_uid = 0, si_status = 46527424, si_utime = 0, si_stime = 0}, _sigfault = {si_addr = 0x1, si_addr_lsb = -3136}, _sigpoll = {si_band = 1, si_fd = 46527424}, _sigsys = {_call_addr = 0x1, _syscall = 46527424, _arch = 0}}}
        oldtype = 0
        result = <optimized out>
        ss = {__val = {2147483648, 0 <repeats 15 times>}}
#1  0x00007f1e71b72182 in start_thread (arg=0x7f1e72e379c0) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f1e72e379c0
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139768753256896, -842023072022440978, 0, 0, 139768753257600, 139768753256896, 751095896206955502, 751092973284971502}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#2  0x00007f1e6ff7347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 1 (Thread 0x7f1e72ded9c0 (LWP 22168)):
#0  0x00007f1e71b79ee9 in __libc_waitpid (pid=22195, stat_loc=0xbb9e20, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
        resultvar = 22195
        oldtype = 0
#1  0x000000000051fd7c in ?? ()
No symbol table info available.
#2  <signal handler called>
No locals.
#3  0x00000000005263a1 in SDLFB::UpdateColors() ()
No symbol table info available.
#4  0x00000000005271a2 in SDLFB::SDLFB(int, int, bool, SDL_Window*) ()
No symbol table info available.
#5  0x00000000005274cf in SDLVideo::CreateFrameBuffer(int, int, bool, DFrameBuffer*) ()
No symbol table info available.
#6  0x00000000006b93be in V_DoModeSetup(int, int, int) ()
No symbol table info available.
#7  0x00000000006b9687 in IVideo::SetResolution(int, int, int) ()
No symbol table info available.
#8  0x00000000006b9032 in V_Init2() ()
No symbol table info available.
#9  0x0000000000559d34 in D_DoomMain() ()
No symbol table info available.
#10 0x00000000005078df in main ()
No symbol table info available.
```
Any idea what is the problem or how can I fix it?

Thanks.

**Comment by michaelkrax** [comment]
Have you tried the following to get the latest version of ViZDoom?

git clone https://github.com/mwydmuch/ViZDoom
cd ViZDoom
# use pip3 for Python3
sudo pip install .

It looks more like generic issue with your audio driver based on the error message though. 

Is sound working on that machine in general? Is sound working when you install and play ZDoom (which ViZDoom is based upon)?
