### ISSUE TITLE
Getting multiprocessing lock error when running vizdoom and pytorch program on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Hybrid-SyntaX** [mwydmuch/ViZDoom#320]
Hello, whenever I try to run my  program on WSL, I get the following error. I'm pretty new to this, so I don't know how to solve this problem.

**Setup**   
- Windows 10 x64   
- Ubuntu 14 (on WSL)  
- Python 2.7.14  (Anaconda 2)  
- OpenAI Gym 0.9.5  
- Vizdoom 1.1.4   
- doom-py 0.0.14  
- ppaquette/gym-doom  
- pytorch 0.0.12

```
    (doomenv) hybridsyntax@Blacklynx:/mnt/f/_TUTORIALS/ai/doom/code$ python ai.py  > wsl.log
    [2018-05-25 18:21:44,354] Making new env: ppaquette/DoomCorridor-v0
    [2018-05-25 18:21:44,365] Clearing 2 monitor files from previous run (because force=True was provided)
    Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
    Traceback (most recent call last):
      File "ai.py", line 155, in <module>
        memory.run_steps(200)
      File "/mnt/f/_TUTORIALS/ai/doom/code/experience_replay.py", line 70, in run_steps
        entry = next(self.n_steps_iter) # 10 consecutive steps
      File "/mnt/f/_TUTORIALS/ai/doom/code/experience_replay.py", line 21, in __iter__
        state = self.env.reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 104, in reset
        return self._reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/wrappers/monitoring.py", line 39, in _reset
        observation = self.env.reset(**kwargs)
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 104, in reset
        return self._reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 311, in _reset
        observation = self.env.reset(**kwargs)
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 104, in reset
        return self._reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/wrappers/frame_skipping.py", line 33, in _reset
        return self.env.reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 104, in reset
        return self._reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 283, in _reset
        return self.env.reset(**kwargs)
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 104, in reset
        return self._reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/wrappers/time_limit.py", line 49, in _reset
        return self.env.reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym/gym/core.py", line 104, in reset
        return self._reset()
      File "/mnt/f/_TUTORIALS/ai/doom/gym-doom/ppaquette_gym_doom/doom_env.py", line 244, in _reset
        return self._load_level()
      File "/mnt/f/_TUTORIALS/ai/doom/gym-doom/ppaquette_gym_doom/doom_env.py", line 157, in _load_level
        'singleton lock in memory.')
    gym.error.Error: [ViZDoomUnexpectedExitException, ViZDoomErrorException] VizDoom exited unexpectedly. This is likely caused by a missing multiprocessing lock. To run VizDoom across multiple processes, you need to pass a lock when you configure the env [e.g. env.configure(lock=my_multiprocessing_lock)], or create and close an env before starting your processes [e.g. env = gym.make("DoomBasic-v0"); env.close()] to cache a singleton lock in memory.
    [2018-05-25 18:21:44,696] Finished writing results. You can upload them to the scoreboard via gym.upload('/mnt/f/_TUTORIALS/ai/doom/code/videos')
    (doomenv) hybridsyntax@Blacklynx:/mnt/f/_TUTORIALS/ai/doom/code$
```

Thanks in advance

**Comment by Miffyli** [comment]
The error stems from `ppaquette/gym-doom` code, not ViZDoom. That particular code has not been updated in a while and may not function with current version of ViZDoom anymore.

The error, while explaining about locks, may be result of any kind of error that occured when booting up ViZDoom ([see here](https://github.com/ppaquette/gym-doom/blob/master/ppaquette_gym_doom/doom_env.py#L126)). It is hard to say from this output what the real error was.

**Comment by Hybrid-SyntaX** [comment]
Thanks for help
I can confirm, that this issue is specific to WSL. While, I could run the [basic example ]([url](http://vizdoom.cs.put.edu.pl/tutorial#short) ) on Ubuntu (VirtualBox) with no problem, I get the following error on WSL, which seems somewhat similar.

```
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
Traceback (most recent call last):
  File "basic_vizdoom.py", line 9, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.
```

I tried to run a fake display by running this command, and still get the same error.
`xvfb-run -s "-screen 0 1400x900x24" bash`

**Comment by Hybrid-SyntaX** [comment]
Upgrading the Ubuntu on WSL to the latest version (18.04) and running a fake display solved the problem.

For me it was running the following commands on WSL.
`sudo -S env RELEASE_UPGRADER_NO_SCREEN=1 do-release-upgrade
sudo apt-get upgrade -y
sudo apt-get update
`
