### ISSUE TITLE
Import fails due to bad naming scheme.

### ISSUE THREAD

**Issue by biggzlar** [mwydmuch/ViZDoom#333]
This is the error message.

```
This interpreter version: '3.6.0' doesn't match with version of the interpreter ViZDoom was compiled with: 3.6
```

Temporary solution:
Simply go to vizdooms `__init__.py` and change the line `_COMPILED_PYTHON_VERSION = "3.6"` to `_COMPILED_PYTHON_VERSION = "3.6.0"`.

This should probably be handled better in a future version.

**Comment by mwydmuch** [comment]
Hi @biggzlar,
thank you for reporting, could you provide information about your OS, CMake version and python distribution? In most cases version extraction works properly.

**Comment by biggzlar** [comment]
Hi @mwydmuch,
thanks for your reply. Here are my system details:
```
OS: macOS High Sierra 10.13.4
CMake: 3.8.2
Python: 3.6.0, running in virtualenv version 15.1.0
```

**Comment by nkashy1** [comment]
Had this exact same issue with Python3.8.

Could not install vizdoom from pip - I still don't know why, but I decided to just build from source instead of trying to debug make via the Python build script.

Built with the same virtual environment activated that I subsequenty tried to `import vizdoom` under.

Built vizdoom successfully and copied the `build/bin/python3/pip_package` directory into my site packages as `vizdoom`.

Tried to `import vizdoom` and got this error message:
```
>>> import vizdoom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fuzzyfroghunter/dev/vizdoom/.vizdoom/lib/python3.8/site-packages/vizdoom/__init__.py", line 8, in <module>
    raise SystemError(
SystemError: This interpreter version: '3.8.0' doesn't match with version of the interpreter ViZDoom was compiled with: 3.8
```

Just going to go and modify the version in the `<site-packages>/vizdoom/__init__.py`, but I'd like to know what the underlying issue is. Reproducing my current installation process would be hacky.

System details:
```
OS (lsb_release -a):
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

CMake (cmake --version):
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Python (python --version):
Python 3.8.0

Make (make --version):
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Hope that helps. Would really like to understand why the `pip install` didn't work, but perhaps that should be a separate bug.

**Comment by Miffyli** [comment]
Hmm. I just tried with conda environment on Ubuntu 16.04 LTS (cmake 3.10.2, python 3.8.3), and both  `pip install vizdoom` and `pip install git+https://github.com/mwydmuch/ViZDoom` install vizdoom correctly. The former does throw a compilation error, but it still did work expected (importing, creating and initializing `DoomGame` works).

**Comment by mwydmuch** [comment]
This was fixed some time ago, so I'm closing the issue.
