### ISSUE TITLE
AttributeError : basic.py failed

### ISSUE THREAD

**Issue by ParkGeonYeong** [mwydmuch/ViZDoom#365]
Hi, I am using ubuntu 18.04, conda 4.5.11 with python 3.6.7 and installed most current version of vizdoom by git cloning.
However, when i tried to run basic.py, it returns error such as:

> Traceback (most recent call last):
  File "/home/geonyoung/ViZDoom/examples/python/basic.py", line 52, in <module>
    game.set_objects_info_enabled(True)
AttributeError: 'vizdoom.vizdoom.DoomGame' object has no attribute 'set_objects_info_enabled'

After i skipped this line, 'set_sectors_info_enabled' make exactly same error.

By the way, Thank you for your great supports and projects!

**Comment by mwydmuch** [comment]
Hi @ParkGeonYeong, are you sure than you installed the current master version?
After installing using (the version should be 1.1.8):
```
pip install git+https://github.com/mwydmuch/ViZDoom
```
The example works fine for me.

**Comment by mihahauke** [comment]
I've run into the same error for 1.1.7. It works for 1.1.8. @ParkGeonYeong Can you confirm it is the case for you too?

**Comment by blearn-cmu** [comment]
I have the same problem using Windows 10, conda 4.6.2, python 3.7.2. I used the pre-compiled Windows binaries for release 1.1.7.

When can we expect the 1.1.8 pre-compiled Windows binaries?

**Comment by blearn-cmu** [comment]
Oops, sorry this was user error. All I had to do was move to the 1.1.7 tag of the source tree.

$ git checkout tag/1.1.7

**Comment by nainglinwai112** [comment]
> Hi, I am using ubuntu 18.04, conda 4.5.11 with python 3.6.7 and installed most current version of vizdoom by git cloning.
> However, when i tried to run basic.py, it returns error such as:
> 
> > Traceback (most recent call last):
> > File "/home/geonyoung/ViZDoom/examples/python/basic.py", line 52, in 
> > game.set_objects_info_enabled(True)
> > AttributeError: 'vizdoom.vizdoom.DoomGame' object has no attribute 'set_objects_info_enabled'
> 
> After i skipped this line, 'set_sectors_info_enabled' make exactly same error.
> 
> By the way, Thank you for your great supports and projects!

is the error solved

**Comment by huangzhengbin** [comment]
I have some problems ,please help me!Iet me give you a brief account of how I built it:
First,I downloaded the windows binaries 1.1.7Python 3.7 (64-bit), and copy it to the 
       C:\ProgramData\Anaconda3\envs\py1\Lib\site-packages,so I can successfully import vizdoom.
Second,I clone the vizdoom from the Github to the local,then I open the cmd, move to the file until 
       examples/python, when I carry out the command of "python basic.py",here are the error:
Traceback (most recent call last):
  File "basic.py", line 52, in <module>
    game.set_objects_info_enabled(True)
AttributeError: 'vizdoom.vizdoom.DoomGame' object has no attribute 'set_objects_info_enabled'
        So what should I do?Please help me!Thank you!

**Comment by TolgaDaSilva** [comment]
Set_objects_info_enabled is only available in version 1.1.8. 
So you have to build it yourself or use it on Linux or Mac.

**Comment by hzt-1999** [comment]
> only

Can you describe it in more detail and how to solve it？

**Comment by hzt-1999** [comment]
> > Hi, I am using ubuntu 18.04, conda 4.5.11 with python 3.6.7 and installed most current version of vizdoom by git cloning.
> > However, when i tried to run basic.py, it returns error such as:
> > > Traceback (most recent call last):
> > > File "/home/geonyoung/ViZDoom/examples/python/basic.py", line 52, in
> > > game.set_objects_info_enabled(True)
> > > AttributeError: 'vizdoom.vizdoom.DoomGame' object has no attribute 'set_objects_info_enabled'
> > 
> > 
> > After i skipped this line, 'set_sectors_info_enabled' make exactly same error.
> > By the way, Thank you for your great supports and projects!
> 
> is the error solved

Can you describe it in more detail and how to solve it？

**Comment by romulofff** [comment]
Hi, I'm using Ubuntu 20.04, Python 3.8.10 and I have the same error 
> AttributeError: 'vizdoom.vizdoom.DoomGame' object has no attribute 'set_soft_sound_enabled'

I tried reducing my code to this 3 lines, and still had the same problem:
```
import vizdoom
game = vizdoom.DoomGame()
game.set_soft_sound_enabled(True)
game.init()
```

I installed vizdoom first with `pip install vizdoom`. Then tried `pip install git+https://github.com/mwydmuch/ViZDoom` and it failed again. Any fix for this?
