### ISSUE TITLE
unable to install vizdoom on pytlhon3.7

### ISSUE THREAD

**Issue by rnunziata** [mwydmuch/ViZDoom#383]
pip3 install doom-py

```
Requirement already satisfied: doom-py in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (0.0.15)
Requirement already satisfied: numpy in /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages (from doom-py) (1.16.2)
```

python3.7

```
Python 3.7.2 (default, Feb 13 2019, 20:54:21) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vizdoom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/vizdoom/__init__.py", line 12, in <module>
    from .vizdoom import __version__ as __version__
ImportError: libboost_filesystem.so.1.64.0: cannot open shared object file: No such file or directory
```

Nor can I compile from source as it fails on finding a boost header asio.hpp

**Comment by Miffyli** [comment]
`doom-py` is pretty old so there may easily be some version mismatches and whatnot.

For building: Make sure you have installed [all the dependencies, including Boost](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md#-linux).
