### ISSUE TITLE
basic example crashing

### ISSUE THREAD

**Issue by semihcanturk** [mwydmuch/ViZDoom#409]
After pip installing ViZDoom as instructed, I'm getting the following error when running the basic.py example:
```
(base) Semihs-MBP:python semo$ python basic.py
libc++abi.dylib: terminating with uncaught exception of type boost::interprocess::lock_exception: boost::interprocess::lock_exception
Traceback (most recent call last):
  File "basic.py", line 99, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.
```

No crash log was generated.

### Versions
vizdoom-1.1.8
macOS 10.14.6
Python environment

How can I get around this? Thanks in advance!

**Comment by mihahauke** [comment]
What is your version of boost (and prefereably all libs that are needed by vizdoom) ?

**Comment by semihcanturk** [comment]
boost 1.71.0
cmake 3.14.3
clang 11.0.0
sdl2 2.0.10
julia 1.2.0

**Comment by hzt-1999** [comment]
> After pip installing ViZDoom as instructed, I'm getting the following error when running the basic.py example:
> 
> ```
> (base) Semihs-MBP:python semo$ python basic.py
> libc++abi.dylib: terminating with uncaught exception of type boost::interprocess::lock_exception: boost::interprocess::lock_exception
> Traceback (most recent call last):
>   File "basic.py", line 99, in <module>
>     game.init()
> vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.
> ```
> 
> No crash log was generated.
> 
> ### Versions
> vizdoom-1.1.8 macOS 10.14.6 Python environment
> 
> How can I get around this? Thanks in advance!

@semihcanturk Hi, semihcanturk! I met the same problem, have you solved it? Can you give me some advice?

**Comment by Miffyli** [comment]
@hzt-1999 can you provide more information on what are you trying to run (code) and what is your system (os, version, python version, vizdoom version, etc).

**Comment by hzt-1999** [comment]
OS: Ubuntu20.04 LTS
python: 3.6.15
vizdoom: 1.1.11
basic.py:
`#!/usr/bin/env python3

#####################################################################
# This script presents how to use the most basic features of the environment.
# It configures the engine, and makes the agent perform random actions.
# It also gets current state and reward earned with the action.
# <episodes> number of episodes are played. 
# Random combination of buttons is chosen for every action.
# Game variables from state and last reward are printed.
#
# To see the scenario description go to "../../scenarios/README.md"
#####################################################################

import os
from random import choice
from time import sleep
import vizdoom as vzd


if __name__ == "__main__":
    # Create DoomGame instance. It will run the game and communicate with you.
    game = vzd.DoomGame()

    # Now it's time for configuration!
    # load_config could be used to load configuration instead of doing it here with code.
    # If load_config is used in-code configuration will also work - most recent changes will add to previous ones.
    # game.load_config("../../scenarios/basic.cfg")

    # Sets path to additional resources wad file which is basically your scenario wad.
    # If not specified default maps will be used and it's pretty much useless... unless you want to play good old Doom.
    game.set_doom_scenario_path(os.path.join(vzd.scenarios_path, "basic.wad"))

    # Sets map to start (scenario .wad files can contain many maps).
    game.set_doom_map("map01")

    # Sets resolution. Default is 320X240
    game.set_screen_resolution(vzd.ScreenResolution.RES_640X480)

    # Sets the screen buffer format. Not used here but now you can change it. Default is CRCGCB.
    game.set_screen_format(vzd.ScreenFormat.RGB24)

    # Enables depth buffer.
    game.set_depth_buffer_enabled(True)

    # Enables labeling of in game objects labeling.
    game.set_labels_buffer_enabled(True)

    # Enables buffer with top down map of the current episode/level.
    game.set_automap_buffer_enabled(True)

    # Enables information about all objects present in the current episode/level.
    game.set_objects_info_enabled(True)

    # Enables information about all sectors (map layout).
    game.set_sectors_info_enabled(True)

    # Sets other rendering options (all of these options except crosshair are enabled (set to True) by default)
    game.set_render_hud(False)
    game.set_render_minimal_hud(False)  # If hud is enabled
    game.set_render_crosshair(False)
    game.set_render_weapon(True)
    game.set_render_decals(False)  # Bullet holes and blood on the walls
    game.set_render_particles(False)
    game.set_render_effects_sprites(False)  # Smoke and blood
    game.set_render_messages(False)  # In-game messages
    game.set_render_corpses(False)
    game.set_render_screen_flashes(True)  # Effect upon taking damage or picking up items

    # Adds buttons that will be allowed to use.
    # This can be done by adding buttons one by one:
    # game.clear_available_buttons()
    # game.add_available_button(vzd.Button.MOVE_LEFT)
    # game.add_available_button(vzd.Button.MOVE_RIGHT)
    # game.add_available_button(vzd.Button.ATTACK)
    # Or by setting them all at once:
    game.set_available_buttons([vzd.Button.MOVE_LEFT, vzd.Button.MOVE_RIGHT, vzd.Button.ATTACK])
    # Buttons that will be used can be also checked by:
    print("Available buttons:", [b.name for b in game.get_available_buttons()])

    # Adds game variables that will be included in state.
    # Similarly to buttons, they can be added one by one:
    # game.clear_available_game_variables()
    # game.add_available_game_variable(vzd.GameVariable.AMMO2)
    # Or:
    game.set_available_game_variables([vzd.GameVariable.AMMO2])
    print("Available game variables:", [v.name for v in game.get_available_game_variables()])

    # Causes episodes to finish after 200 tics (actions)
    game.set_episode_timeout(200)

    # Makes episodes start after 10 tics (~after raising the weapon)
    game.set_episode_start_time(10)

    # Makes the window appear (turned on by default)
    game.set_window_visible(True)

    # Turns on the sound. (turned off by default)
    # game.set_sound_enabled(True)
    # Because of some problems with OpenAL on Ubuntu 20.04, we keep this line commented,
    # the sound is only useful for humans watching the game.

    # Sets the living reward (for each move) to -1
    game.set_living_reward(-1)

    # Sets ViZDoom mode (PLAYER, ASYNC_PLAYER, SPECTATOR, ASYNC_SPECTATOR, PLAYER mode is default)
    game.set_mode(vzd.Mode.PLAYER)

    # Enables engine output to console.
    #game.set_console_enabled(True)

    # Initialize the game. Further configuration won't take any effect from now on.
    game.init()

    # Define some actions. Each list entry corresponds to declared buttons:
    # MOVE_LEFT, MOVE_RIGHT, ATTACK
    # game.get_available_buttons_size() can be used to check the number of available buttons.
    # 5 more combinations are naturally possible but only 3 are included for transparency when watching.
    actions = [[True, False, False], [False, True, False], [False, False, True]]

    # Run this many episodes
    episodes = 10

    # Sets time that will pause the engine after each action (in seconds)
    # Without this everything would go too fast for you to keep track of what's happening.
    sleep_time = 1.0 / vzd.DEFAULT_TICRATE  # = 0.028

    for i in range(episodes):
        print("Episode #" + str(i + 1))

        # Starts a new episode. It is not needed right after init() but it doesn't cost much. At least the loop is nicer.
        game.new_episode()

        while not game.is_episode_finished():

            # Gets the state
            state = game.get_state()

            # Which consists of:
            n = state.number
            vars = state.game_variables
            screen_buf = state.screen_buffer
            depth_buf = state.depth_buffer
            labels_buf = state.labels_buffer
            automap_buf = state.automap_buffer
            labels = state.labels
            objects = state.objects
            sectors = state.sectors

            # Games variables can be also accessed via:
            #game.get_game_variable(GameVariable.AMMO2)

            # Makes a random action and get remember reward.
            r = game.make_action(choice(actions))

            # Makes a "prolonged" action and skip frames:
            # skiprate = 4
            # r = game.make_action(choice(actions), skiprate)

            # The same could be achieved with:
            # game.set_action(choice(actions))
            # game.advance_action(skiprate)
            # r = game.get_last_reward()

            # Prints state's game variables and reward.
            print("State #" + str(n))
            print("Game variables:", vars)
            print("Reward:", r)
            print("=====================")

            if sleep_time > 0:
                sleep(sleep_time)

        # Check how the episode went.
        print("Episode finished.")
        print("Total reward:", game.get_total_reward())
        print("************************")

    # It will be done automatically anyway but sometimes you need to do it in the middle of the program...
    game.close()
`
Errors:
libc++abi.dylib: terminating with uncaught exception of type boost::interprocess::lock_exception: boost::interprocess::lock_exception
Traceback (most recent call last):
  File "basic.py", line 99, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.
 
Thank you!

**Comment by Miffyli** [comment]
Hmm that one is tricky, as it seems to stem from the Boost library :s. I assume you installed the dependencies with the command from tutorials (the long list of `apt get` installs)? If not, could you try doing it with that?

If that fails, you could try the [conda](https://github.com/mwydmuch/ViZDoom#conda) way which installs boost libraries from conda repos.

**Comment by verbiix** [comment]
Hey, I just double checked that I'm able to run `basic.py` on my local machine. I spun up a conda environment with the following requirements and it worked perfect on my first try.

It's been a while, so maybe this issue kind of worked itself out by now. If not I'd recommend a debug session with ChatGPT.

```
annotated-types==0.7.0
certifi==2025.1.31
charset-normalizer==3.4.1
click==8.1.8
cloudpickle==3.1.1
docker-pycreds==0.4.0
Farama-Notifications==0.0.4
filelock==3.18.0
fsspec==2025.3.2
gitdb==4.0.12
GitPython==3.1.44
gymnasium==1.1.1
idna==3.10
Jinja2==3.1.6
MarkupSafe==3.0.2
mpmath==1.3.0
networkx==3.4.2
opencv-python==4.11.0
opencv-python-headless==4.11.0
platformdirs==4.3.7
protobuf==5.29.4
psutil==7.0.0
pydantic==2.11.3
pydantic_core==2.33.1
pygame==2.6.1
PyYAML==6.0.2
requests==2.32.3
sentry-sdk==2.25.1
setproctitle==1.3.5
six==1.17.0
smmap==5.0.2
sympy==1.13.3
torch==2.2.2
typing-inspection==0.4.0
typing_extensions==4.13.1
urllib3==2.3.0
vizdoom==1.2.4
wandb==0.19.9
```

**Comment by verbiix** [comment]
My best guess is maybe something to do with your linker/system paths?
