### ISSUE TITLE
Won't Install 

### ISSUE THREAD

**Issue by Tylersuard** [mwydmuch/ViZDoom#426]
Ubuntu 16, Python 3.6
This didn't work with either venv or conda.

Error message:

ERROR: Command errored out with exit status 1:
   command: /home/tyler/anaconda3/envs/vizdoomenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wt7u87qa/ViZDoom/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wt7u87qa/ViZDoom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u31nezwo --python-tag cp36
       cwd: /tmp/pip-install-wt7u87qa/ViZDoom/

And then later:

 /home/tyler/anaconda3/envs/vizdoomenv/lib/libharfbuzz.so.0: undefined reference to `FT_Done_MM_Var'
  /home/tyler/anaconda3/envs/vizdoomenv/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
  collect2: error: ld returned 1 exit status
  src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:8920: recipe for target 'bin/vizdoom' failed
  make[2]: *** [bin/vizdoom] Error 1
  CMakeFiles/Makefile2:937: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
  make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
  Makefile:83: recipe for target 'all' failed
  make: *** [all] Error 2
  
  Installation failed, you may be missing some dependencies.
  Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-wt7u87qa/ViZDoom/setup.py", line 119, in <module>
      keywords=['vizdoom', 'doom', 'ai', 'deep learning', 'reinforcement learning', 'research']
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-wt7u87qa/ViZDoom/setup.py", line 82, in run
      subprocess.check_call(['make', '-j', str(cpu_cores)])
    File "/home/tyler/anaconda3/envs/vizdoomenv/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-j', '7']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for ViZDoom
  Running setup.py clean for ViZDoom
Failed to build ViZDoom
Installing collected packages: ViZDoom
    Running setup.py install for ViZDoom ... error
    ERROR: Command errored out with exit status 1:

Please help me install Vizdoom!  I'm really excited to use it.

**Comment by Miffyli** [comment]
Did you make sure you installed the dependencies as listed [here](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md)? 

Virtual environments (e.g. conda) have caused some issues in the past, so I recommend you also try on standard installation of Python, if possible. You can find bunch of related issues by searching "environment" and/or "conda" here in the issues list, those could shed some light.

**Comment by mwydmuch** [comment]
An old issue with no response from the author, closing.
