### ISSUE TITLE
Multiple instance hang infinitely within pytest

### ISSUE THREAD

**Issue by Trinkle23897** [mwydmuch/ViZDoom#487]
## Description

I'd like to use vizdoom to test with one of my codebase with [pytest](https://pytest.org/), typically for multi-agent environment. However, when I tried to do this, I found it hanging infinitely when launching multiple process within pytest, but instead if I directly run the script, it would run successfully. I couldn't figure out what's happening and thus seeking your kindly help.

Here is the step:

1. install pytest: `pip install pytest`;
2. modify `examples/python/multiple_instances.py`:
   - add `+viz_connect_timeout 4` in `game.add_game_args`
   - change the main function to:
```python
def test_2p():
    p1 = Process(target=player1)
    p1.start()
    player2()
    print("Done")

if __name__ == '__main__':
    test_2p()
```
   - the full script is attached: [multiple_instances.py](https://github.com/mwydmuch/ViZDoom/files/6844994/multiple_instances.txt)

3. `cd examples/python`
4. `pytest multiple_instances.py --durations 0 -v`

Here's the result:
```bash
pytest multiple_instances.py --durations 0 -v 
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.8.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/trinkle/github/ViZDoom
plugins: cov-2.11.1
collected 1 item                                                                                                                                                                                                   

multiple_instances.py::test_2p FAILED

===================================================================================================== FAILURES =====================================================================================================
_____________________________________________________________________________________________________ test_2p ______________________________________________________________________________________________________

    def test_2p():
        p1 = Process(target=player1)
        p1.start()
>       player2()

multiple_instances.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def player2():
        game = DoomGame()
    
        # game.load_config('../config/basic.cfg')
        # or
        game.load_config('../../scenarios/multi_duel.cfg')
        game.add_game_args("-join 127.0.0.1 +viz_connect_timeout 4")
        game.add_game_args("+name Player2 +colorset 3")
    
>       game.init()
E       vizdoom.vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.

multiple_instances.py:58: ViZDoomUnexpectedExitException
----------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------


----------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
Press 'Q' to abort network game synchronization.
Waiting for players: .  [ 1/ 2]Press 'Q' to abort network game synchronization.
Contacting host: /
Timeout, network game synchronization aborted.
Timeout, network game synchronization aborted.Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/trinkle/github/ViZDoom/examples/python/multiple_instances.py", line 26, in player1
    game.init()
vizdoom.vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.
================================================================================================ slowest durations =================================================================================================
4.27s call     examples/python/multiple_instances.py::test_2p

(2 durations < 0.005s hidden.  Use -vv to show these durations.)
============================================================================================= short test summary info ==============================================================================================
FAILED multiple_instances.py::test_2p - vizdoom.vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.
================================================================================================ 1 failed in 4.44s =================================================================================================

```

However, if I directly run `./multiple_instances.py`, all things work well:
```bash
$ ./multiple_instances.py

Press 'Q' to abort network game synchronization.
Waiting for players: .  [ 1/ 2]Press 'Q' to abort network game synchronization.
Got connect from node 1.                
Waiting for players: .. [ 2/ 2]
Sending all here.                       

Total players: 2                        

Waiting for other players: .. [ 2/ 2]
Console player number: 1                
Received All Here, sending ACK.         

Go                                      
Total players: 2                        
Console player number: 1                
Received All Here, sending ACK.         
Received "Go."                          

Total players: 2                        

Exchanging game information.
Found Player1 (node 1, player 1)        
Found Player2 (node 1, player 2)        
Found Player2 (node 0, player 2)        




Episode #1
Episode finished!
Player1 frags: 5.0
Player2 frags: 4.0
Episode #2
Episode finished!
Player1 frags: 2.0
Player2 frags: 3.0
Done
```

## ViZDoom version

1.1.8

## Version
OS platform, distribution: Ubuntu 20.04 (but this can be reproduced in many Linux container)
Environment (GCC, Python, Java, Lua versions etc.):
```python
In [1]: import sys

In [2]: print(sys.version, sys.platform)
3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] linux
```

**Comment by Miffyli** [comment]
Possibly related issue: https://github.com/mwydmuch/ViZDoom/issues/391 (see comments on "stuck")

I am not sure how pytest works underneath, but ViZDoom has been finicky with `threading` module, with multiplayer connections being a big culprit in the past. Quickly googling this up lands in [similar-sounding issues](https://github.com/scipy/scipy/issues/11835) (altho not with Pytest), with no clear fix available apart from some hacky tricks which do not apply here.

**Comment by Trinkle23897** [comment]
Thanks! I've successfully run this sample-factory's unittest with pytest and actually it works! Maybe there's something hacky I should pay attention to...

**Comment by Trinkle23897** [comment]
Update: there are two test cases in [sample-factory](https://github.com/alex-petrenko/sample-factory/blob/master/sample_factory/envs/doom/multiplayer/tests/test_vizdoom_multiplayer.py), however, only `test_doom_multiagent_parallel` can work within pytest. I've successfully used the `Process` to let the above code run successfully, i.e.,
```python
def test_multiplayer_cig():
  """Multiagent cig game can only work in Process while using pytest."""
  worker = Process(target=test_2p, args=())
  worker.start()
  worker.join()
```
